[package]
name = "fluid_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
log = "0.4.27"
simple_logger = "5.0.0"
ash = "0.38.0+1.3.281"
glam = "0.30.9"
rayon = "1.11.0"
gpu-allocator = "0.28.0"

[build-dependencies]
shaderc = "0.10.1"
